### ISSUE TITLE
Search cards not appearing although count of results is correct

### ISSUE THREAD

**Issue by allysonlister** [FAIRsharing/fairsharing.github.io#571]
**Describe the bug**
Good morning! Both @delphinedauga and I have been trying to search both on "MIRAGE" and on its expanded text: https://preview.fairsharing.org/#/search?q=Minimum%20Information%20Required%20for%20A%20Glycomics%20Experiment Weirdly, the search says it returns 5 results (probably correct), but there are no search cards displayed.

Other searches (e.g. https://preview.fairsharing.org/#/search?q=microarray) seem to be working properly, but I can't scroll through the search cards that are on the first page of results. @terazus says that this is related to the MIRAGE issue.

**To Reproduce**
1. Go to https://preview.fairsharing.org/#/search?q=Minimum%20Information%20Required%20for%20A%20Glycomics%20Experiment 
2. Look at results.

Other queries include https://preview.fairsharing.org/#/search?q=microarray and "MIRAGE".

**Expected behavior**
I expect the 5 search cards to be visible.

**Screenshots**
![1to5ofnone](https://user-images.githubusercontent.com/143586/99660536-64b5ee80-2a5a-11eb-9a0c-84d5938da597.png)

![scroll-microarray](https://user-images.githubusercontent.com/143586/99660581-77302800-2a5a-11eb-81cf-3471d4f750f1.gif)

**Operating system and browser version**
Ubuntu 20.04.1 LTS 64 bit + Chrome Version 87.0.4280.66 (Official Build) (64-bit)

**Additional context**
As an aside, we decided to search the preview server because the production server was returning 0 results, when it should be returning about 7: https://fairsharing.org/search/?q=Minimum+Information+Required+for+A+Glycomics+Experiment . This may be relevant for you finding the issue with the preview server, or might not.

Perhaps some of this just has something to do with the recent migration?

**Comment by knirirr** [comment]
I'm seeing a lot of these in the console:

```
TypeError: can't access property "val", e[t.linkedRecord.registry] is undefined
    associatedRecords RecordsCardStack.vue:184
    associatedRecords RecordsCardStack.vue:183
    et RecordsCardStack.vue:1
```

I'll look into this if I can, though I'm still having trouble running the code on my Mac. 
Bizarrely, I cannot reproduce the log messages or any of the symptoms shown above on my Ubuntu latptop, with the same data as on api.fairsharing.org (local instance) and the latest dev branch of the client.  This would appear to be the fault of the data in the latest migration.

**Comment by knirirr** [comment]
I think this is fixed now, results visible currently at https://dev--fairsharing.netlify.app/#/search?q=Minimum%20Information%20Required%20for%20A%20Glycomics%20Experiment
Preview will be updated next time there's a merge to master from dev. 
So, please feel free to close if satisfied.

**Comment by knirirr** [comment]
I'll assume that this is satisfactory and close it.

**Comment by knirirr** [comment]
Looks like this is also affecting grid view.

**Comment by allysonlister** [comment]
The names of the records all seem to be correct now, thank you!

As @knirirr noted, the grid view is still broken (i.e. doesn't show all cards that it should in the grid), although the names it does show are correct.

**Comment by knirirr** [comment]
I fixed the grid view last week, though you won't see the change on preview until it is merged to master. 

https://github.com/FAIRsharing/fairsharing.github.io/commit/956a217c3e7ce9cf2b641f719ac716aa36f26bc2

**Comment by allysonlister** [comment]
Thanks, @knirirr
